version: 2
executorType: docker
containerInfo:
  - image: markfirmware/ufpc-circleci2-testing-26
stages:
  build:
    workDir: ~/temperature
    steps:
      - type: checkout
      - name: build
        type: shell
        command: scripts/-build.sh
      - name: qemu test
        type: shell
        command: scripts/linux-test-with-qemu.sh && mv build-test-output artifacts
      - name: save artifacts
        type: artifacts-store
        path: artifacts
        destination: temperature
