version: 2
executorType: docker
containerInfo:
  - image: markfirmware/ufpc-do-not-use2
    cmd: ["/bin/bash"]
stages:
  build:
    workDir: ~/temperature
    steps:
      - type: checkout
      - type: shell
        shell: /bin/bash
        command: echo temperature at $(date)
