#!/usr/bin/python

import os, parse, select, shutil, socket, subprocess, sys
from time import sleep

outputfolder = 'run-qemu-output'

class TcpChannel:
    def __init__ (self, name, port):
#       print name, port
        self.name = name
        self.port = port
        self.socket = socket.socket ()
        self.socket.connect (('127.0.0.1', self.port))
        self.logfile = open ('{}/{}.txt'.format (outputfolder, self.name), 'a')
        sleep (1)
    def writeline (self, line):
#       print '{}>>>>{}'.format (self.name, line)
        self.logfile.write (line + '\n')
        self.socket.sendall (line + '\n')
    def writekeyboardline (self, line):
#       print '{}>>>>{}'.format (self.name, line)
        self.logfile.write (line + '\n')
        self.socket.sendall (line + '\r')
    def drain (self):
        try:
            while ([], [], []) != select.select ([self.socket], [], [], 0):
                sleep (0.001)
                data = self.socket.recv (1)
                self.logfile.write (data)
                if data == "":
                    break
        except:
            pass
    def finishquit (self, process):
        while process.returncode == None:
            sleep (0.001)
            process.poll ()
            if ([], [], []) != select.select ([self.socket], [], [], 0):
                sys.stdout.write (self.socket.recv (1))
    def close (self):
        self.logfile.close ()
        self.socket.close ()

def bash (lines):
    for line in lines:
#       print 'bash >>', line
        subprocess.check_call (line, shell=True)

bash (['rm -rf {}/'.format (outputfolder),
       'mkdir -p {}'.format (outputfolder)])

qemuprocess = subprocess.Popen (["qemu-system-arm",
                                 "-M", "versatilepb",
                                 "-cpu", "cortex-a8",
                                 "-kernel", "kernel.bin",
                                 "-m", "256M",
                                 "-usb",
                                 "-display", "none",
                                 "-monitor", "tcp:127.0.0.1:38001,server",
                                 "-serial", "tcp:127.0.0.1:38002,server",
                                 "-serial", "tcp:127.0.0.1:38003,server"],
                                stdout=subprocess.PIPE,
                                stderr=subprocess.PIPE)

sleep (2)
monitor = TcpChannel ('monitor', 38001)
applog  = TcpChannel ('applog',  38002)
appapi  = TcpChannel ('appapi',  38003)

applog.drain ()
monitor.writeline ('screendump {}/screen-01.ppm'.format (outputfolder))
for i in range (1, 10):
    appapi.writekeyboardline ('line {}'.format (i))
sleep (7)
monitor.writeline ('screendump {}/screen-02.ppm'.format (outputfolder))

sleep (2)
applog.drain ()
appapi.drain ()
monitor.drain ()
monitor.writeline ('quit')
sleep (2)
applog.drain ()
appapi.drain ()
monitor.drain ()
monitor.finishquit (qemuprocess)

#print
#print 'qemu return code', qemuprocess.returncode

monitor.close ()
applog.close ()
appapi.close ()

bash (['convert {0}/screen-01.ppm {0}/screen-01.png'.format (outputfolder),
       'convert {0}/screen-02.ppm {0}/screen-02.png'.format (outputfolder),
       'rm {}/*.ppm'.format (outputfolder),
       'cat {}/applog.txt'.format (outputfolder)])
